version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/current/
hooks:
  BeforeInstall:
    - location: supple/ci/AWSCodeDeploy/nginx/prebuild.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: supple/ci/AWSCodeDeploy/nginx/build.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: supple/ci/AWSCodeDeploy/nginx/start.sh
      timeout: 500
      runas: root
